import Head from 'next/head'
import { Header } from '../components/Header'
import { Navbar } from '../components/Navbar'
import { Services } from '../components/Services/Services'
import { Works } from '../components/Works'
import { HowItWorks } from '../components/HowItWorks'
import { Pricing } from '../components/Pricing'
import { Features } from '../components/Features'
import { Feedback } from '../components/Feedback'
import { Footer } from '../components/Footer'
import { Index } from '../components/FAQ'

export default function Home() {
  return (
    <div>
      <Head>
        <title>UNIK Media Group - Insurance</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Navbar />
      <Header />
      <Services />
      <Works />
      <HowItWorks />
      <Pricing />
      <Features />
      <Feedback />
      <Index />
      <Footer />

    </div>
  )
}
